server:
  port: 8088

spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      management:
        context-path: /provider/actuator
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /provider/health
    status-page-url: /provider/actuator/info
    home-page-url: /provider

version: 2.0.0