server:
  port: 8088

spring:
  application:
    name: consumer
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

version: A