server:
  port: 8087

spring:
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

version: AAA-DEV